services:
  pids-system:
    build: .
    container_name: pids_container
    command: tail -f /dev/null
    network_mode: "host"
    
    privileged: true
    devices:
      - "/dev/v4l2-subdev0:/dev/v4l2-subdev0"
      - "/dev/v4l2-subdev1:/dev/v4l2-subdev1"
      - "/dev/media0:/dev/media0"
      - "/dev/media1:/dev/media1"
      - "/dev/video0:/dev/video0"
      - "/dev/dma_heap:/dev/dma_heap" 
    
    volumes:
      - ./output:/app/output
      - ./codes:/app/codes
      - /run/udev:/run/udev:ro
      - /home/tim/.Xauthority:/root/.Xauthority:rw
    
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
    
    restart: unless-stopped
    